name: Build package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Arch Linux PKGBUILD builder action
      uses: 2m/arch-pkgbuild-builder@v1.9
      with:
        target: 'pkgbuild'
        pkgname: 'wd719x-firmware'

    - uses: actions/upload-artifact@v1
      with:
        name: wd719x-firmware
        path: wd719x-firmware-*.pkg.tar.xz
